project:
  type: website
  output-dir: "."

website:
  title: "Seamus Flaherty"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - project.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/seamusjflaherty/
      - icon: github
        menu:
          - text: Github Account
            href: https://github.com/SeamusJFlaherty/
          - text: Source Code
            href: https://github.com/SeamusJFlaherty/SeamusJFlaherty.github.io/

format:
  html:
    theme: morph    #superhero # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

