project:
  type: website
  output-dir: docs

website:
  title: "Seamus Flaherty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: instagram
        menu:
          - text: Instagram
            href: https://instagram.com/sflaherty357
          - text: Snapchat
            href: https://www.snapchat.com/add/spdr9044
          - text: Twitter
            href: https://x.com/sflaherty357
      - icon: linkedin
        href: https://www.linkedin.com/in/seamus-flaherty-45819332b/
      - icon: github
        menu:
          - text: Github Account
            href: https://github.com/SeamusJFlaherty/
          - text: Source Code
            href: https://github.com/SeamusJFlaherty/SeamusJFlaherty.github.io/

format:
  html:
    theme: superhero  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

